#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr 11 13:20:41 2024

@author: esmeekool
"""

import pandas as pd
import matplotlib.pyplot as plt



data= pd.read_csv('/Users/esmeekool/Desktop/dataset_mood_smartphone.csv', delimiter=',')
data.info()
data.head()
data.columns


# (number of) participants
participants = data['id'].unique()
n = len(participants)

# (number of) variables
variables = data['variable'].unique()
nr_variables = len(variables)

# datapoints per participant (= unequal)
data['id'].value_counts() 


#Data cleaning
data['id'][5]